### ISSUE TITLE
삭제 메서드 제안

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#44]
![image](https://user-images.githubusercontent.com/35232655/159929123-87edbd81-ff2d-4605-8e4d-b86d53c547b6.png)

룩푹 삭제 메서드로
POST .../lookPage/image 가 직관적이지 않은 것 같아요.
DELETE .../lookPage 로 바꾸는 건 어떤가요?

**Comment by choiwoonsik** [comment]
네 그렇게 수정할게요
