### ISSUE TITLE
이미지 업로드 방식에 대한 제안

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#45]
![image](https://user-images.githubusercontent.com/35232655/159929914-704fd95c-ec14-46a4-a79b-59b5e497a94a.png)

새로운 룩 페이지를 만들 때와 룩 페이지를 수정할 때 보내야하는 데이터가 일관적이지 않은 것 같아요.

### 저는 다음과 같은 방법이 좋을 것 같아요.
1. 이미지를 업로드하는 api 는 전체 api 중 단 하나만 존재한다. - 이 api 는 response 로 uuid 를 반환한다.
2. 룩 페이지 생성, 수정, 마이페이지 프로필 사진 수정 등 이미지를 업로드하거나 수정해야하는 api 에서 image 파라미터로 file 을 전송하는 대신 uuid 를 전달한다.

### 예시
![image](https://user-images.githubusercontent.com/35232655/159931768-13a79664-b10c-4d9c-ab37-0cce51fd94e7.png)
![image](https://user-images.githubusercontent.com/35232655/159931985-0b983662-a50b-4fdb-81a2-8f53383d0d86.png)

위 예제는 프로필 변경 api 입니다.
클라이언트에서 image 업로드 먼저 수행하여 uuid 를 얻은 뒤 프로필 변경 요청을 보내면 됩니다.

**Comment by choiwoonsik** [comment]
민지님이랑 얘기해보고 말씀드릴게요.

**Comment by choiwoonsik** [comment]
@HamBP uuid방식에 대해서 궁금한게 있습니다.

현재 사진을 업로드하면
- https://sigma-image-bucket.s3.ap-northeast-2.amazonaws.com/upload/memberLookImage/C5EB3584-3871-4F46-98E8-43D0DB500353_1_201_a_2022-03-25_21_13_56.jpeg

위와같이 해당 이미지가 업로드 되어있는 s3의 url을 반환하고 있는데 uuid를 드리면 어떻게 이미지를 띄울 수 있는지 궁금해서요.
그래도 가능한가요?

만약 그게 불가능하다면 업로드 주소를 반환하게 하고 이미지 업로드를 통합하게 하는 방식을 원하실까요?

**Comment by HamBP** [comment]
아 예시 api 에서는 uuid 가 유니크하다는 특성을 이용하여
.../image/{uuid} 를 통해 이미지를 다운받을 수 있는 api 가 제공되었네요.

![image](https://user-images.githubusercontent.com/35232655/160139306-04c45f57-c7d9-4c8a-9a17-a60df21e9a14.png)

uuid 로 응답값을 받더라도 이 uuid 를 이용해 url 을 얻어내는 방식으로 가져오는 거라 이미지는 지금처럼 url 로 내려주시면 됩니다!
다만 사진 변경과 같은 요청에서 이미지를 업로드하는 부분과 데이터를 변경하는 부분을 분리할 수 있는 방법이라, 확인해 보시고 혹시 이게 더 낫다고 느끼시면 변경하시면 되고 그렇지 않다면 그대로 두셔도 됩니다!

**Comment by HamBP** [comment]
만약 변경한다면
image: File
위 타입에서 아래 타입으로 바뀌면 됩니다!
image : String (url)

**Comment by choiwoonsik** [comment]
아 이해했습니다. 민지님이랑 상의해서 말씀드릴게요.

**Comment by choiwoonsik** [comment]
@HamBP 준영님이 말씀하신 방법대로 변경하기로 했습니다. 수정 완료되면 말씀드릴게요!
