### ISSUE TITLE
코디네이터 작품 수정/삭제

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#53]
고객 룩북 수정/삭제는 적용했습니다!
혹시 코디네이터 작품 수정 및 삭제는 어떤 api 를 이용하면 될까요?
리뷰 수정 및 삭제도 같이 질문드립니다!
![image](https://user-images.githubusercontent.com/35232655/160564513-bfb43bc5-4880-45a7-9a4d-13c7dfa407a6.png)

**Comment by bigand32** [comment]
죄송해여 금방추가해드릴게요

**Comment by HamBP** [comment]
엥 아니에여 뭐가 죄송해요 ㅋㅋㅋㅋ

**Comment by choiwoonsik** [comment]
리뷰 수정 삭제 낼까지 올릴게요!
