### ISSUE TITLE
코디네이터 목록 조회 api 문의

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#55]
![image](https://user-images.githubusercontent.com/35232655/160852632-81138b59-6f92-4ad4-b9cc-55347166733e.png)

![image](https://user-images.githubusercontent.com/35232655/160853013-59d21af5-d508-4d5b-aa9d-d72f97d366c1.png)

이 api 이용하면 crdi@crdi.com 가 나와야할 것 같은데 data 에 아무것도 안 담겨서 나오는 거 같아요
추가로 코디네이터 프로필 상세보기로 들어가기 위해서는 배열 안에 email 값도 같이 주셔야할 것 같습니다!

**Comment by bigand32** [comment]
넹
