### ISSUE TITLE
코디네이터 계좌 등록 api 추가 요청

### ISSUE THREAD

**Issue by QuiverDance** [Sigma-i-2022/backend#62]
코디네이터가 수익을 지급 받을 계좌를 등록하는 api 가 없어서 추가 부탁 드립니다.

**Comment by choiwoonsik** [comment]
아까 회의때 말씀드렸다시피 금융결제원 api말고 토스페이먼츠의 서브몰 등록으로 할 예정이라 현재 기능 개발 중에 있습니다.
일단 계좌등록 부분은 미뤄주세요!
