### ISSUE TITLE
/v1/api/crdi/work/all 동작이 바뀐 것 같아요.

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#67]
![image](https://user-images.githubusercontent.com/35232655/164254799-fc14c2b8-30cc-4586-8a59-1020cd13dd86.png)

/v1/api/crdi/work/list

위 경로로 요청했을 때 위 스크린샷과 같이 4개의 작품 목록이 나옵니다.

![image](https://user-images.githubusercontent.com/35232655/164254997-0125d54a-2c9a-4ecd-89fe-46aa7cc3e1d3.png)

/v1/api/crdi/work/all

위 경로로 요청했을 때에도 4개의 작품이 확인 되었었는데, 이슈 수정 이후로 조회가 안 되는 것 같아요.

**Comment by choiwoonsik** [comment]
이게 보니깐 저장된 코디네이터의 SEQ랑 이메일이 다르게 저장되어서 그렇네요
SEQ 는 crdi@crdi.com 회원의 SEQ 이고
email은 woon@test.com 이 들어가있어서 
woon@test.com으로 조회하면 잘 나옵니다.

왜 잘못 저장되었는지는 다시 봐볼게요.
