### ISSUE TITLE
코디네이터 작품 삭제

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#70]
코디네이터 작품 삭제가 안 되는 것 같은데 확인해 주시면 감사합니다.
![image](https://user-images.githubusercontent.com/35232655/165532684-4425b3d3-3888-4dac-8f25-601fd05b8712.png)

스웨거로 테스트했고 성공 응답으로 나오지만 계속 조회가 되는 것 같아요.

**Comment by HamBP** [comment]
수정한 거 확인했습니다!
![image](https://user-images.githubusercontent.com/35232655/165546033-f4deae90-2acb-46e2-94ed-00cabafbcc12.png)
관련 api 가 하나 더 있는데, 여기도 수정되어야 할 것 같아요!

**Comment by choiwoonsik** [comment]
이거  완료된건가요?

**Comment by HamBP** [comment]
작품을 삭제하면
/v1/api/crdi/work/all 에서는 정상적으로 사라지지만
/v1/api/crdi/work/list 에서는 여전히 응답에 포함되어 오는 상태입니다!

개인적인 생각으로는 activateYn 값에 따라 filter 하는 로직이 service 가 아니라 repository 에서 이루어지면 좋을 거 같아요

**Comment by choiwoonsik** [comment]
확인했습니다. 수정할게요
