### ISSUE TITLE
woon@test.com 작품 리스트 조회가 갑자기 안 됩니다!

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#72]
![image](https://user-images.githubusercontent.com/35232655/165546810-a7e06381-65e1-49ad-8e4c-7978fd684420.png)

http://13.125.39.167:9090/v1/api/crdi/work/all?crdiEmail=woon%40test.com&page=0&size=20

위 요청이 갑자기 400 이 뜨는데 왜 그런지 잘 모르겠네요

**Comment by choiwoonsik** [comment]
<img width="639" alt="스크린샷 2022-05-02 오후 9 42 45" src="https://user-images.githubusercontent.com/42247724/166235372-7cd19735-0928-43cf-a42b-2fcebaadb514.png">
널포인터 exception이 발생해서 오류가 난거였습니다. 이전에 저장된거랑 이후 신고 기능이 추가되면서 충돌나서 발생한 경우입니다. 해당 데이터는 지울게요.
