### ISSUE TITLE
단순 질문입니다! 두 api 의 차이를 잘 모르겠습니다!

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#73]
![image](https://user-images.githubusercontent.com/35232655/165547336-ab1f4325-624c-4f30-aeec-3326a2768713.png)

위 두 개 api 의 용도 차이를 잘 모르겠습니다.

**Comment by choiwoonsik** [comment]
음 파라미터가 누락되어 있긴했는데 위에건 tag, 전문가여부, 자기소개를 등록하고/ 밑에건 자기소개만 수정할 때 사용하는 용도입니다.

**Comment by HamBP** [comment]
음... 등록이라는 부분이 잘 이해가 안 됩니다... 사용자 flow 에서는 등록하는 과정이 없지 않나요?

자기소개 뿐만 아니라 태그나 전문가 여부를 수정할 때에는 post 요청으로 보내면 되는 건가요?

**Comment by choiwoonsik** [comment]
네네 맞습니다. 둘다 사용자 입장에선 수정이라 좀 애매하기하네요.
