### ISSUE TITLE
고객 룩북 추가할 때 키워드(태그)1,2,3

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#74]
![image](https://user-images.githubusercontent.com/35232655/165551793-ae44ae87-4b52-472f-b6af-d50951d21168.png)

키워드 1, 2, 3 값으로 보낼 수 있는 값이 제한적인 것 같아요. 코디네이터는 수정되었는데, 고객쪽이 수정이 안 된 것 같습니다.

**Comment by choiwoonsik** [comment]
수정했습니다.
