### ISSUE TITLE
리뷰 작성자 프로필 사진 url 요청합니다!

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#81]
![image](https://user-images.githubusercontent.com/35232655/169313230-d3e87e43-8618-4a73-babe-1e6e3c1aa46f.png)

위 사진에서 keiee 의 프로필 사진 url 이 필요합니다!

**Comment by choiwoonsik** [comment]
넵 알겠습니다.

**Comment by choiwoonsik** [comment]
회원 이메일로 profile image url 요청하는 api를 만들어드리는것도 괜찮을까요?
