### ISSUE TITLE
답글 삭제 확인해주세요

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#82]
![image](https://user-images.githubusercontent.com/35232655/169655123-1146c380-593f-45c0-8999-e76970dbf2c6.png)

코디 이메일 : crdi@crdi.com 에 대한 답글 seq 7 삭제 요청이 성공 응답을 받았으나, 리뷰 목록 조회했을 때 결과가 같습니다.

**Comment by choiwoonsik** [comment]
확인했습니다.
