### ISSUE TITLE
api 도큐먼트 수정 요청합니다.

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#83]
![image](https://user-images.githubusercontent.com/35232655/169662388-a104caaa-ceb2-4c98-99d7-ea180c73352e.png)

yymmdd 로 보내면 실패하고 yyyymmdd 로 보내야 성공하는 거 같아요

**Comment by choiwoonsik** [comment]
해당 api가 아니라 서브몰 관리 api 사용하셔야됩니다. 금융결제원 api는 상용버전 사용이 불가해서 사용안할거에요.
api 목록에서도 지울게요. 혼동드려서 죄송해요.
