### ISSUE TITLE
/v1/api/openapi/realname 문의

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#84]
![image](https://user-images.githubusercontent.com/35232655/169662707-41945dc2-5ed6-4ba1-bd18-cad791246ed6.png)

/v1/api/openapi/realname 요청 결과 response 가 잘 이해되지 않습니다.
success 와 message 는 성공처럼 보이는데 data 는 false 라고 나옵니다.

**Comment by choiwoonsik** [comment]
해당 api가 아니라 서브몰 관리 api 사용하셔야됩니다. 금융결제원 api는 상용버전 사용이 불가해서 사용안할거에요.
api 목록에서도 지울게요. 혼동드려서 죄송해요.
