### ISSUE TITLE
계좌 등록 후 조회가 안 되는 것 같아요.

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#85]
crdi@crdi.com 이메일로 제 계좌 등록 후 성공 응답을 받았으나 조회했을 때 실패 응답을 받습니다.]

![image](https://user-images.githubusercontent.com/35232655/169662833-9b8b33e1-7397-4c08-a51a-0fbf21fe7534.png)

stack trace 가 message 로 나오는 것 같아요.

**Comment by choiwoonsik** [comment]
해당 api가 아니라 서브몰 관리 api 사용하셔야됩니다. 금융결제원 api는 상용버전 사용이 불가해서 사용안할거에요.
api 목록에서도 지울게요. 혼동드려서 죄송해요.
