### ISSUE TITLE
서브몰 삭제 api 문의드려요

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#90]
![image](https://user-images.githubusercontent.com/35232655/170820217-f7883a10-023d-4be5-ba25-2c7a91e9dae4.png)

삭제가 안 되는 것 같아 확인 부탁드립니다!

**Comment by choiwoonsik** [comment]
배포용 서버 설정파일에 url이 잘못 적혀있었습니다. 수정했습니다.
