### ISSUE TITLE
서브몰 전체 조회 api 문의드립니다.

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#91]
![image](https://user-images.githubusercontent.com/35232655/170820280-66822f6a-80e8-4365-97e3-b8520afecc21.png)

스웨거에서 돌렸는데 조회가 안 되는 것 같습니다

**Comment by choiwoonsik** [comment]
배포용 서버 설정파일에 url이 잘못 적혀있었습니다. 수정했습니다.

참고로 현재 테스트계정이라 서브몰 전체조회는 모든 토스페이먼츠 테스트 계정이랑 공유되니깐 참고해주세요.
