### ISSUE TITLE
서브몰 등록 문의드립니다.

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#92]
![image](https://user-images.githubusercontent.com/35232655/170820450-c322d5fe-1bb3-48c5-922a-0d76e8557342.png)

일단 위 사진처럼 보내면 400 응답이 돌아옵니다.

궁금한 점은 두 가지입니다!
1. 개인 계좌의 경우 type 에 "개인" 을 입력하면 되는 건가요?
2. 개인 계좌일 경우 상호명, 대표명에는 무엇을 적어야 하나요?

**Comment by choiwoonsik** [comment]
배포용 서버 설정파일에 url이 잘못 적혀있었습니다. 수정했습니다.

1. 네
2. 말그대로 상호명이랑 대표명을 자유롭게 적으면됩니다. 이에대한 유효성 검증 로직은 따로 없습니다.
추가) 은행, 예금주, 계좌번호만 잘 적어주면 됩니다. 그리고 현재 테스트 계정이므로 대부분의 은행은 안됩니다. 제가 테스트할 땐 국민은행만 되길래 그걸로만 진행했습니다.
<img width="442" alt="스크린샷 2022-05-29 오후 2 51 23" src="https://user-images.githubusercontent.com/42247724/170854242-081343bf-77f4-4e65-9a11-8da291f00829.png">

**Comment by HamBP** [comment]
확인했습니다.
