### ISSUE TITLE
서브몰 수정 문의드립니다.

### ISSUE THREAD

**Issue by HamBP** [Sigma-i-2022/backend#93]
![image](https://user-images.githubusercontent.com/35232655/170820623-27868597-7b24-4d41-8d5a-c0776e7f44bc.png)

등록 부분에는 개인 사업자인지 법인 사업자인지 여부를 묻는데, 수정 요청에서는 필요하지 않은 건가요?

**Comment by choiwoonsik** [comment]
네 개인 사업자 <-> 법인 사업자 간 변환은 불가하고 기존 서브몰 취소 후 재요청해야합니다.

위 요청으로 변경되는건 1. 계좌관련 정보(은행명, 계좌번호, 예금주) 2. 상호명 3. 대표명 4. 사업자등록번호 입니다.
즉, 입력한 정보로 모두 교체됩니다.

**Comment by HamBP** [comment]
이해했습니다!
